name: Parse and build posts
on:
    push:
        branches: [ master ]
jobs:
    parse-posts:
        name: Parse posts
        runs-on: ubuntu-latest
        steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        # Runs a single command using the runners shell
        - name: Run a one-line script
          run: echo Hello, world!
        - name: Get diff
          run: git diff --name-only ${{ github.event.before }} ${{ github.sha }}