name: Build and deploy
on:
    push:
        branches: [ master ]
jobs:
    parse-posts:
        name: Build and deploy
        runs-on: ubuntu-latest
        steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v1
          with:
            node-version: '12'
        - name: Install yarn and dependencies
          run: npx yarn
        # Runs a single command using the runners shell
        - name: Run a one-line script
          run: echo Hello, world!
        - name: Generate RSS feed
          run: yarn workspace bin create-rss
        - name: Build and export
          run: yarn workspace blog build-export
        - name: Upload statics to S3
          env:
            AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
            AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          run: yarn workspace bin upload-statics

        # - name: Get diff
        #   run: git diff --name-status --output diff.txt ${{ github.event.before }} ${{ github.sha }}
        # - name: Read diff
        #   run: |
        #     echo Reading diff file...
        #     cat diff.txt
        # - name: Run script
        #   run: npx ts-node -s ./.github/actions/read-diff.ts